name: release
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 10 * * *'
env:
  version: version-4.6.4.7568
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@master
      - name: Get version number
        run: |
          ls -la
          VERSION=$(cat version.yaml | grep 'version' | cut -d ' ' -f4)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Use version number in next step
        run: |
          echo $VERSION # use the version number here
      - name: replace version in Dockerfiel
        run: sed -i 's/VERSION/${{ env.VERSION }}/g' Dockerfile
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: loeken/radarr:${{ env.version }}
          context: .
          no-cache: true
